aaa:
  act-name: testhaha,aaa
server:
  port: 8080
logging:
  config: classpath:log4j2-dev.xml
#
#mybatis:
#  type-aliases-package: com.example.demo.domain
#  configuration:
#    #自动驼峰式
#    map-underscore-to-camel-case: true
#  #mapper文件扫描
#  mapper-locations: mapper/mapping/*.xml,mybatis/extend/*.xml

spring:
  datasource:
#    name: master
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/sandytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2b8&useAffectedRows=true&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 123456
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 6
#      maximum-pool-size: 16
#      pool-name: hikari-master
#      connection-test-query: SELECT 1
    master:
      name: masterDb
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/sandytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2b8&useAffectedRows=true&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 6
        maximum-pool-size: 16
        pool-name: hikari-master
        connection-test-query: SELECT 1
    slave:
      name: slaveDb
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/sandytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2b8&useAffectedRows=true&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        maximum-pool-size: 15
        pool-name: hikari-slave
        connection-test-query: SELECT 1
  redis:
    database: 0
    password: ''
    port: 6379
    host: 127.0.0.1
    # commandTimeout，执行命令3s超时
    timeout: 3000
    lettuce:
      pool:
        #连接池最大连接数
        max-active: 3
        #连接池最小空闲连接数
        min-idle: 2
        #连接池最大空闲连接数
        max-idle: 3
        #连接池获取连接最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #在关闭客户端连接之前等待任务处理完成的最长时间，在这之后，无论任务是否执行完成，都会被执行器关闭，默认100ms
      shutdown-timeout: 1000

