server:
  port: 8080
logging:
  config: classpath:log4j2-pro.xml
mybatis:
  type-aliases-package: com.king.demo.dto
  configuration:
    #自动驼峰式
    map-underscore-to-camel-case: true
  #mapper文件扫描
  mapper-locations: mybatis/mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sandytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2b8&useAffectedRows=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      idle-timeout: 30000
      pool-name: hikari
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    password: ''
    port: 6379
    host: 127.0.0.1
    # commandTimeout，执行命令3s超时
    timeout: 3000
    lettuce:
      pool:
        #连接池最大连接数
        max-active: 300
        #连接池最小空闲连接数
        min-idle: 10
        #连接池最大空闲连接数
        max-idle: 300
        #连接池获取连接最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #在关闭客户端连接之前等待任务处理完成的最长时间，在这之后，无论任务是否执行完成，都会被执行器关闭，默认100ms
      shutdown-timeout: 1000


